#!/usr/bin/env python3
"""
Enhanced version generator with more git information.
"""

import subprocess
import sys
import os
import re
from datetime import datetime
from pathlib import Path

class VersionGenerator:
    def __init__(self, repo_path='.'):
        self.repo_path = Path(repo_path)

    def run_git_command(self, cmd):
        """Run git command and return output."""
        try:
            result = subprocess.run(
                ['git'] + cmd,
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                check=True
            )
            return result.stdout.strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            return None

    def get_commit_info(self):
        """Get comprehensive commit information."""
        info = {}

        # Get short commit hash (7 characters by default)
        info['hash_short'] = self.run_git_command(['rev-parse', '--short', 'HEAD'])

        # Get full commit hash
        info['hash_full'] = self.run_git_command(['rev-parse', 'HEAD'])

        # Get commit date in various formats
        commit_date = self.run_git_command(['log', '-1', '--format=%cd', '--date=short'])
        if commit_date:
            info['date_iso'] = commit_date  # YYYY-MM-DD
            info['date_compact'] = commit_date.replace('-', '')  # YYYYMMDD
        else:
            current_date = datetime.now().strftime("%Y-%m-%d")
            info['date_iso'] = current_date
            info['date_compact'] = current_date.replace('-', '')

        # Get tag information if available
        info['tag'] = self.run_git_command(['describe', '--tags', '--always'])

        # Check if there are uncommitted changes
        status = self.run_git_command(['status', '--porcelain', '-uno'])
        st=status.split() if bool(status) else []
        info['dirty'] = bool(status) and not (len(st)==2 and st[0]=='M' and st[1].endswith('arduino.json'))

        # Get branch name
        branch = self.run_git_command(['branch', '--show-current'])
        info['branch'] = branch if branch else 'detached'
        print(info)
        return info

    def generate_version_string(self, commit_info, format_str="{date_iso}_{branch}_{hash_short}{dirty_marker}"):
        """Generate version string from commit info."""
        dirty_marker = "-dirty" if commit_info['dirty'] else ""

        # Prepare template variables
        vars_dict = {
            **commit_info,
            'dirty_marker': dirty_marker,
            'year': commit_info['date_iso'][:4],
            'month': commit_info['date_iso'][5:7],
            'day': commit_info['date_iso'][8:10]
        }

        # Format the version string
        version = format_str.format(**vars_dict)

        # If tag is available and we're not dirty, use tag as base
        #if commit_info['tag'] and not commit_info['dirty']:
            # Remove hash from tag description if present
        #    tag = re.sub(r'-g[0-9a-f]+$', '', commit_info['tag'])
        #    version = tag
        return version

    def generate_header(self, output_file='version.h'):
        """Generate the version.h header file."""
        commit_info = self.get_commit_info()
        version_string = self.generate_version_string(commit_info)

        # Create header guard from output filename
        header_guard = output_file.upper().replace('.', '_').replace('/', '_')

        header_content = f"""/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by {Path(__file__).name} */

#ifndef {header_guard}
#define {header_guard}

/* Program version string */
#define PROGRAM_VERSION "{version_string}"

/* Version components */
#define VERSION_DATE "{commit_info['date_compact']}"
#define VERSION_HASH "{commit_info['hash_short'] or 'unknown'}"
#define VERSION_HASH_FULL "{commit_info['hash_full'] or 'unknown'}"
#define VERSION_BRANCH "{commit_info['branch']}"
#define VERSION_TAG "{commit_info['tag'] or 'none'}"
#define VERSION_DIRTY {str(commit_info['dirty']).lower()}

/* Helper macros for version checking */
#define VERSION_AT_LEAST(date_str) (strcmp(VERSION_DATE, date_str) >= 0)
#define VERSION_IS_DIRTY() (VERSION_DIRTY)

#endif /* {header_guard} */
"""

        # Write file if changed
        output_path = Path(output_file)
        write_needed = True

        if output_path.exists():
            with open(output_path, 'r') as f:
                if f.read() == header_content:
                    write_needed = False

        if write_needed:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w') as f:
                f.write(header_content)
            print(f"Generated {output_file} with version: {version_string}")
        else:
            print(f"{output_file} is up to date")

        return version_string, commit_info

def main():
    """Command line interface."""
    import argparse

    parser = argparse.ArgumentParser(
        description='Generate version header from git repository',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                    # Generate version.h
  %(prog)s -o include/version.h  # Output to specific location
  %(prog)s --format "{year}.{month}.{day}-{hash_short}"  # Custom format
  %(prog)s --print            # Print version to stdout
        """
    )

    parser.add_argument(
        '-o', '--output',
        default='version.h',
        help='Output header file (default: version.h)'
    )
    parser.add_argument(
        '--format',
        default='{date_compact}-{hash_short}',
        help='Format string for version (default: {date_compact}-{hash_short})'
    )
    parser.add_argument(
        '--repo',
        default='.',
        help='Path to git repository (default: current directory)'
    )
    parser.add_argument(
        '--print',
        action='store_true',
        help='Print version string to stdout'
    )
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Show detailed version information'
    )

    args = parser.parse_args()

    generator = VersionGenerator(args.repo)
    version, info = generator.generate_header(args.output)

    if args.print:
        print(version)

    if args.verbose:
        print("\nDetailed version information:")
        print(f"  Version string: {version}")
        print(f"  Commit date:    {info['date_iso']}")
        print(f"  Commit hash:    {info['hash_short']}")
        print(f"  Full hash:      {info['hash_full']}")
        print(f"  Branch:         {info['branch']}")
        print(f"  Tag:            {info['tag']}")
        print(f"  Dirty:          {info['dirty']}")

    return 0

if __name__ == '__main__':
    sys.exit(main())